/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as MyJudgesRouteRouteImport } from './routes/my/judges/route'
import { Route as MyDogsRouteRouteImport } from './routes/my/dogs/route'
import { Route as MyCompetitionsRouteRouteImport } from './routes/my/competitions/route'
import { Route as MyJudgesIndexRouteImport } from './routes/my/judges/index'
import { Route as MyDogsIndexRouteImport } from './routes/my/dogs/index'
import { Route as MyCompetitionsIndexRouteImport } from './routes/my/competitions/index'
import { Route as MyCompetitionsIdRouteRouteImport } from './routes/my/competitions/$id/route'
import { Route as MyJudgesListIndexRouteImport } from './routes/my/judges/list/index'
import { Route as MyDogsListIndexRouteImport } from './routes/my/dogs/list/index'
import { Route as MyCompetitionsListIndexRouteImport } from './routes/my/competitions/list/index'
import { Route as MyCompetitionsIdIndexRouteImport } from './routes/my/competitions/$id/index'
import { Route as MyCompetitionsIdStagesStageIdIndexRouteImport } from './routes/my/competitions/$id/stages/$stageId/index'
import { Route as MyCompetitionsIdStagesStageIdEventsEventIdIndexRouteImport } from './routes/my/competitions/$id/stages/$stageId/events/$eventId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJudgesRouteRoute = MyJudgesRouteRouteImport.update({
  id: '/my/judges',
  path: '/my/judges',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDogsRouteRoute = MyDogsRouteRouteImport.update({
  id: '/my/dogs',
  path: '/my/dogs',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCompetitionsRouteRoute = MyCompetitionsRouteRouteImport.update({
  id: '/my/competitions',
  path: '/my/competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJudgesIndexRoute = MyJudgesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyJudgesRouteRoute,
} as any)
const MyDogsIndexRoute = MyDogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyDogsRouteRoute,
} as any)
const MyCompetitionsIndexRoute = MyCompetitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyCompetitionsRouteRoute,
} as any)
const MyCompetitionsIdRouteRoute = MyCompetitionsIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MyCompetitionsRouteRoute,
} as any)
const MyJudgesListIndexRoute = MyJudgesListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => MyJudgesRouteRoute,
} as any)
const MyDogsListIndexRoute = MyDogsListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => MyDogsRouteRoute,
} as any)
const MyCompetitionsListIndexRoute = MyCompetitionsListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => MyCompetitionsRouteRoute,
} as any)
const MyCompetitionsIdIndexRoute = MyCompetitionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyCompetitionsIdRouteRoute,
} as any)
const MyCompetitionsIdStagesStageIdIndexRoute =
  MyCompetitionsIdStagesStageIdIndexRouteImport.update({
    id: '/stages/$stageId/',
    path: '/stages/$stageId/',
    getParentRoute: () => MyCompetitionsIdRouteRoute,
  } as any)
const MyCompetitionsIdStagesStageIdEventsEventIdIndexRoute =
  MyCompetitionsIdStagesStageIdEventsEventIdIndexRouteImport.update({
    id: '/stages/$stageId/events/$eventId/',
    path: '/stages/$stageId/events/$eventId/',
    getParentRoute: () => MyCompetitionsIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my/competitions': typeof MyCompetitionsRouteRouteWithChildren
  '/my/dogs': typeof MyDogsRouteRouteWithChildren
  '/my/judges': typeof MyJudgesRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/my/competitions/$id': typeof MyCompetitionsIdRouteRouteWithChildren
  '/my/competitions/': typeof MyCompetitionsIndexRoute
  '/my/dogs/': typeof MyDogsIndexRoute
  '/my/judges/': typeof MyJudgesIndexRoute
  '/my/competitions/$id/': typeof MyCompetitionsIdIndexRoute
  '/my/competitions/list/': typeof MyCompetitionsListIndexRoute
  '/my/dogs/list/': typeof MyDogsListIndexRoute
  '/my/judges/list/': typeof MyJudgesListIndexRoute
  '/my/competitions/$id/stages/$stageId/': typeof MyCompetitionsIdStagesStageIdIndexRoute
  '/my/competitions/$id/stages/$stageId/events/$eventId/': typeof MyCompetitionsIdStagesStageIdEventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/my/competitions': typeof MyCompetitionsIndexRoute
  '/my/dogs': typeof MyDogsIndexRoute
  '/my/judges': typeof MyJudgesIndexRoute
  '/my/competitions/$id': typeof MyCompetitionsIdIndexRoute
  '/my/competitions/list': typeof MyCompetitionsListIndexRoute
  '/my/dogs/list': typeof MyDogsListIndexRoute
  '/my/judges/list': typeof MyJudgesListIndexRoute
  '/my/competitions/$id/stages/$stageId': typeof MyCompetitionsIdStagesStageIdIndexRoute
  '/my/competitions/$id/stages/$stageId/events/$eventId': typeof MyCompetitionsIdStagesStageIdEventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my/competitions': typeof MyCompetitionsRouteRouteWithChildren
  '/my/dogs': typeof MyDogsRouteRouteWithChildren
  '/my/judges': typeof MyJudgesRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/my/competitions/$id': typeof MyCompetitionsIdRouteRouteWithChildren
  '/my/competitions/': typeof MyCompetitionsIndexRoute
  '/my/dogs/': typeof MyDogsIndexRoute
  '/my/judges/': typeof MyJudgesIndexRoute
  '/my/competitions/$id/': typeof MyCompetitionsIdIndexRoute
  '/my/competitions/list/': typeof MyCompetitionsListIndexRoute
  '/my/dogs/list/': typeof MyDogsListIndexRoute
  '/my/judges/list/': typeof MyJudgesListIndexRoute
  '/my/competitions/$id/stages/$stageId/': typeof MyCompetitionsIdStagesStageIdIndexRoute
  '/my/competitions/$id/stages/$stageId/events/$eventId/': typeof MyCompetitionsIdStagesStageIdEventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my/competitions'
    | '/my/dogs'
    | '/my/judges'
    | '/auth/callback'
    | '/my/competitions/$id'
    | '/my/competitions/'
    | '/my/dogs/'
    | '/my/judges/'
    | '/my/competitions/$id/'
    | '/my/competitions/list/'
    | '/my/dogs/list/'
    | '/my/judges/list/'
    | '/my/competitions/$id/stages/$stageId/'
    | '/my/competitions/$id/stages/$stageId/events/$eventId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/my/competitions'
    | '/my/dogs'
    | '/my/judges'
    | '/my/competitions/$id'
    | '/my/competitions/list'
    | '/my/dogs/list'
    | '/my/judges/list'
    | '/my/competitions/$id/stages/$stageId'
    | '/my/competitions/$id/stages/$stageId/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/my/competitions'
    | '/my/dogs'
    | '/my/judges'
    | '/auth/callback'
    | '/my/competitions/$id'
    | '/my/competitions/'
    | '/my/dogs/'
    | '/my/judges/'
    | '/my/competitions/$id/'
    | '/my/competitions/list/'
    | '/my/dogs/list/'
    | '/my/judges/list/'
    | '/my/competitions/$id/stages/$stageId/'
    | '/my/competitions/$id/stages/$stageId/events/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyCompetitionsRouteRoute: typeof MyCompetitionsRouteRouteWithChildren
  MyDogsRouteRoute: typeof MyDogsRouteRouteWithChildren
  MyJudgesRouteRoute: typeof MyJudgesRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/judges': {
      id: '/my/judges'
      path: '/my/judges'
      fullPath: '/my/judges'
      preLoaderRoute: typeof MyJudgesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/dogs': {
      id: '/my/dogs'
      path: '/my/dogs'
      fullPath: '/my/dogs'
      preLoaderRoute: typeof MyDogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/competitions': {
      id: '/my/competitions'
      path: '/my/competitions'
      fullPath: '/my/competitions'
      preLoaderRoute: typeof MyCompetitionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/judges/': {
      id: '/my/judges/'
      path: '/'
      fullPath: '/my/judges/'
      preLoaderRoute: typeof MyJudgesIndexRouteImport
      parentRoute: typeof MyJudgesRouteRoute
    }
    '/my/dogs/': {
      id: '/my/dogs/'
      path: '/'
      fullPath: '/my/dogs/'
      preLoaderRoute: typeof MyDogsIndexRouteImport
      parentRoute: typeof MyDogsRouteRoute
    }
    '/my/competitions/': {
      id: '/my/competitions/'
      path: '/'
      fullPath: '/my/competitions/'
      preLoaderRoute: typeof MyCompetitionsIndexRouteImport
      parentRoute: typeof MyCompetitionsRouteRoute
    }
    '/my/competitions/$id': {
      id: '/my/competitions/$id'
      path: '/$id'
      fullPath: '/my/competitions/$id'
      preLoaderRoute: typeof MyCompetitionsIdRouteRouteImport
      parentRoute: typeof MyCompetitionsRouteRoute
    }
    '/my/judges/list/': {
      id: '/my/judges/list/'
      path: '/list'
      fullPath: '/my/judges/list/'
      preLoaderRoute: typeof MyJudgesListIndexRouteImport
      parentRoute: typeof MyJudgesRouteRoute
    }
    '/my/dogs/list/': {
      id: '/my/dogs/list/'
      path: '/list'
      fullPath: '/my/dogs/list/'
      preLoaderRoute: typeof MyDogsListIndexRouteImport
      parentRoute: typeof MyDogsRouteRoute
    }
    '/my/competitions/list/': {
      id: '/my/competitions/list/'
      path: '/list'
      fullPath: '/my/competitions/list/'
      preLoaderRoute: typeof MyCompetitionsListIndexRouteImport
      parentRoute: typeof MyCompetitionsRouteRoute
    }
    '/my/competitions/$id/': {
      id: '/my/competitions/$id/'
      path: '/'
      fullPath: '/my/competitions/$id/'
      preLoaderRoute: typeof MyCompetitionsIdIndexRouteImport
      parentRoute: typeof MyCompetitionsIdRouteRoute
    }
    '/my/competitions/$id/stages/$stageId/': {
      id: '/my/competitions/$id/stages/$stageId/'
      path: '/stages/$stageId'
      fullPath: '/my/competitions/$id/stages/$stageId/'
      preLoaderRoute: typeof MyCompetitionsIdStagesStageIdIndexRouteImport
      parentRoute: typeof MyCompetitionsIdRouteRoute
    }
    '/my/competitions/$id/stages/$stageId/events/$eventId/': {
      id: '/my/competitions/$id/stages/$stageId/events/$eventId/'
      path: '/stages/$stageId/events/$eventId'
      fullPath: '/my/competitions/$id/stages/$stageId/events/$eventId/'
      preLoaderRoute: typeof MyCompetitionsIdStagesStageIdEventsEventIdIndexRouteImport
      parentRoute: typeof MyCompetitionsIdRouteRoute
    }
  }
}

interface MyCompetitionsIdRouteRouteChildren {
  MyCompetitionsIdIndexRoute: typeof MyCompetitionsIdIndexRoute
  MyCompetitionsIdStagesStageIdIndexRoute: typeof MyCompetitionsIdStagesStageIdIndexRoute
  MyCompetitionsIdStagesStageIdEventsEventIdIndexRoute: typeof MyCompetitionsIdStagesStageIdEventsEventIdIndexRoute
}

const MyCompetitionsIdRouteRouteChildren: MyCompetitionsIdRouteRouteChildren = {
  MyCompetitionsIdIndexRoute: MyCompetitionsIdIndexRoute,
  MyCompetitionsIdStagesStageIdIndexRoute:
    MyCompetitionsIdStagesStageIdIndexRoute,
  MyCompetitionsIdStagesStageIdEventsEventIdIndexRoute:
    MyCompetitionsIdStagesStageIdEventsEventIdIndexRoute,
}

const MyCompetitionsIdRouteRouteWithChildren =
  MyCompetitionsIdRouteRoute._addFileChildren(
    MyCompetitionsIdRouteRouteChildren,
  )

interface MyCompetitionsRouteRouteChildren {
  MyCompetitionsIdRouteRoute: typeof MyCompetitionsIdRouteRouteWithChildren
  MyCompetitionsIndexRoute: typeof MyCompetitionsIndexRoute
  MyCompetitionsListIndexRoute: typeof MyCompetitionsListIndexRoute
}

const MyCompetitionsRouteRouteChildren: MyCompetitionsRouteRouteChildren = {
  MyCompetitionsIdRouteRoute: MyCompetitionsIdRouteRouteWithChildren,
  MyCompetitionsIndexRoute: MyCompetitionsIndexRoute,
  MyCompetitionsListIndexRoute: MyCompetitionsListIndexRoute,
}

const MyCompetitionsRouteRouteWithChildren =
  MyCompetitionsRouteRoute._addFileChildren(MyCompetitionsRouteRouteChildren)

interface MyDogsRouteRouteChildren {
  MyDogsIndexRoute: typeof MyDogsIndexRoute
  MyDogsListIndexRoute: typeof MyDogsListIndexRoute
}

const MyDogsRouteRouteChildren: MyDogsRouteRouteChildren = {
  MyDogsIndexRoute: MyDogsIndexRoute,
  MyDogsListIndexRoute: MyDogsListIndexRoute,
}

const MyDogsRouteRouteWithChildren = MyDogsRouteRoute._addFileChildren(
  MyDogsRouteRouteChildren,
)

interface MyJudgesRouteRouteChildren {
  MyJudgesIndexRoute: typeof MyJudgesIndexRoute
  MyJudgesListIndexRoute: typeof MyJudgesListIndexRoute
}

const MyJudgesRouteRouteChildren: MyJudgesRouteRouteChildren = {
  MyJudgesIndexRoute: MyJudgesIndexRoute,
  MyJudgesListIndexRoute: MyJudgesListIndexRoute,
}

const MyJudgesRouteRouteWithChildren = MyJudgesRouteRoute._addFileChildren(
  MyJudgesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyCompetitionsRouteRoute: MyCompetitionsRouteRouteWithChildren,
  MyDogsRouteRoute: MyDogsRouteRouteWithChildren,
  MyJudgesRouteRoute: MyJudgesRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
