/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyCompetitionsRouteRouteImport } from './routes/my-competitions/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyCompetitionsIndexRouteImport } from './routes/my-competitions/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as MyCompetitionsListIndexRouteImport } from './routes/my-competitions/list/index'
import { Route as MyCompetitionsIdIndexRouteImport } from './routes/my-competitions/$id/index'

const MyCompetitionsRouteRoute = MyCompetitionsRouteRouteImport.update({
  id: '/my-competitions',
  path: '/my-competitions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCompetitionsIndexRoute = MyCompetitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyCompetitionsRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCompetitionsListIndexRoute = MyCompetitionsListIndexRouteImport.update({
  id: '/list/',
  path: '/list/',
  getParentRoute: () => MyCompetitionsRouteRoute,
} as any)
const MyCompetitionsIdIndexRoute = MyCompetitionsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => MyCompetitionsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-competitions': typeof MyCompetitionsRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/my-competitions/': typeof MyCompetitionsIndexRoute
  '/my-competitions/$id/': typeof MyCompetitionsIdIndexRoute
  '/my-competitions/list/': typeof MyCompetitionsListIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/my-competitions': typeof MyCompetitionsIndexRoute
  '/my-competitions/$id': typeof MyCompetitionsIdIndexRoute
  '/my-competitions/list': typeof MyCompetitionsListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-competitions': typeof MyCompetitionsRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/my-competitions/': typeof MyCompetitionsIndexRoute
  '/my-competitions/$id/': typeof MyCompetitionsIdIndexRoute
  '/my-competitions/list/': typeof MyCompetitionsListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-competitions'
    | '/auth/callback'
    | '/my-competitions/'
    | '/my-competitions/$id/'
    | '/my-competitions/list/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/my-competitions'
    | '/my-competitions/$id'
    | '/my-competitions/list'
  id:
    | '__root__'
    | '/'
    | '/my-competitions'
    | '/auth/callback'
    | '/my-competitions/'
    | '/my-competitions/$id/'
    | '/my-competitions/list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyCompetitionsRouteRoute: typeof MyCompetitionsRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/my-competitions': {
      id: '/my-competitions'
      path: '/my-competitions'
      fullPath: '/my-competitions'
      preLoaderRoute: typeof MyCompetitionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-competitions/': {
      id: '/my-competitions/'
      path: '/'
      fullPath: '/my-competitions/'
      preLoaderRoute: typeof MyCompetitionsIndexRouteImport
      parentRoute: typeof MyCompetitionsRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-competitions/list/': {
      id: '/my-competitions/list/'
      path: '/list'
      fullPath: '/my-competitions/list/'
      preLoaderRoute: typeof MyCompetitionsListIndexRouteImport
      parentRoute: typeof MyCompetitionsRouteRoute
    }
    '/my-competitions/$id/': {
      id: '/my-competitions/$id/'
      path: '/$id'
      fullPath: '/my-competitions/$id/'
      preLoaderRoute: typeof MyCompetitionsIdIndexRouteImport
      parentRoute: typeof MyCompetitionsRouteRoute
    }
  }
}

interface MyCompetitionsRouteRouteChildren {
  MyCompetitionsIndexRoute: typeof MyCompetitionsIndexRoute
  MyCompetitionsIdIndexRoute: typeof MyCompetitionsIdIndexRoute
  MyCompetitionsListIndexRoute: typeof MyCompetitionsListIndexRoute
}

const MyCompetitionsRouteRouteChildren: MyCompetitionsRouteRouteChildren = {
  MyCompetitionsIndexRoute: MyCompetitionsIndexRoute,
  MyCompetitionsIdIndexRoute: MyCompetitionsIdIndexRoute,
  MyCompetitionsListIndexRoute: MyCompetitionsListIndexRoute,
}

const MyCompetitionsRouteRouteWithChildren =
  MyCompetitionsRouteRoute._addFileChildren(MyCompetitionsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyCompetitionsRouteRoute: MyCompetitionsRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
