sonar.projectKey=k9x_frontend
sonar.organization=k9x
sonar.sources=ui/app/src,ui/library/src
sonar.tests=ui/app/src,ui/library/src
sonar.test.inclusions=ui/app/**/*.test.ts,ui/app/**/*.test.tsx,ui/app/**/*.spec.ts,ui/app/**/*.spec.tsx,ui/library/**/*.test.ts,ui/library/**/*.test.tsx,ui/library/**/*.spec.ts,ui/library/**/*.spec.tsx
sonar.coverage.exclusions=**/*.css,**/*.scss,ui/library/src/**/*.stories.ts,ui/library/src/**/*.stories.tsx
sonar.javascript.lcov.reportPaths=.reports/test/total/coverage/lcov.info
sonar.testExecutionReportPaths=.reports/sonar/unit/app/test-report.xml,.reports/sonar/unit/library/test-report.xml,.reports/sonar/e2e/sonar.xml
sonar.qualitygate.wait=false
