import type { StageEventClassificationResponseDTO } from "@/services/fetch-stages/fetchStages.types";

export const defaultClassification: StageEventClassificationResponseDTO = {
  event: { id: "stage-latest-event-1", name: "Agility Standard" },
  competitionName: "Valencia Autumn Trial",
  discipline: { id: "disc-1", name: "Agility" },
  stage: { id: "stage-latest", name: "Valencia Autumn Trial" },
  configuration: { id: "config-1", name: "Standard" },
  lastUpdated: 1_730_050_000_000,
  status: "COMPLETED",
  obdx: {
    scoreCalculation: "AVG",
    judges: [
      { id: "judge-1", name: "Maria Lopez" },
      { id: "judge-2", name: "Jean Dupont" },
    ],
    competitors: [
      {
        position: 1,
        dog: { id: "dog-1", name: "Rex" },
        country: { id: "ES", name: "Spain" },
        owner: "Ana Perez",
        handler: "Ana Perez",
        team: "Team Alpha",
        scoreRating: 1,
        status: "COMPLETED",
        exercises: [],
        totalScore: 98,
        tied: false,
        startOrder: 1,
        bih: false,
        awards: [{ id: "caciob", name: "CACIOB" }],
      },
      {
        position: 2,
        dog: { id: "dog-2", name: "Luna" },
        country: { id: "FR", name: "France" },
        owner: "Marc Soler",
        handler: "Marc Soler",
        team: "Team Beta",
        scoreRating: 1,
        status: "COMPLETED",
        exercises: [],
        totalScore: 95,
        tied: false,
        startOrder: 2,
        bih: false,
        awards: [],
      },
    ],
  },
};
