export enum AppRoutePath {
  HOME = "/",
  STAGES = "/stages",
  AUTH_CALLBACK = "/auth/callback",
  EVENT_DETAIL = "/stages/$id/events/$eventId",
  EVENT_INFO = "/stages/$id/info",
  EVENT_QUALIFICATIONS = "/stages/$id/events/$eventId/qualifications",
  MY_COMPETITIONS = "/my/competitions",
  MY_JUDGES = "/my/judges",
  MY_DOGS = "/my/dogs",
  COMPETITION_DETAIL = "/my/competitions/$id",
  COMPETITION_STAGE_DETAIL = "/my/competitions/$id/stages/$stageId",
  COMPETITION_EVENT_DETAIL = "/my/competitions/$id/stages/$stageId/events/$eventId",
  NOT_FOUND = "/404.html",
  MY_COLLECTIONS = "/my/collections",
  COLLECTION_DETAIL = "/my/collections/$id",
}
